### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by svoeff** [qimingfan10/SAM-VMNet#3]
请问是否能够提供ARCADE公开数据集和私有数据集的下载链接

**Comment by qimingfan10** [comment]
> 请问是否能够提供ARCADE公开数据集和私有数据集的下载链接

你好，以下为ARCADE公开数据集：
https://zenodo.org/records/8386059
私有数据集因许可问题暂时无法提供，谢谢。

**Comment by svoeff** [comment]
> > 询问是否能够提供ARCADE公开数据集和树木数据集的下载链接
> 
> 好，以下为 ARCADE 公开数据集： https://zenodo.org/records/8386059 氧气数据集因许可问题暂时无法提供，谢谢。

好的非常感谢
